name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

defaults:
  run:
    working-directory: pulse-ds

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Build library
        run: npm run build:lib

      - name: Build Storybook
        run: npm run build-storybook

      - uses: actions/upload-artifact@v4
        with:
          name: storybook-build
          path: pulse-ds/dist/storybook
